/*
Gurufocus Data Package API

Testing ETFAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/gurufocus/data-package/sdk/go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_ETFAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ETFAPIService EtfSymbolGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var symbol string

		resp, httpRes, err := apiClient.ETFAPI.EtfSymbolGet(context.Background(), symbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
